import localFont from "next/font/local";
import "./globals.css";

export const metadata = {
  title: "Truss Archive",
  description: "Generated by create next app",
};

const rigidSquare = localFont({
  src: [
    {
      path: "../../public/fonts/RigidSquare-Bold.ttf",
      weight: "700",
    },
    {
      path: "../../public/fonts/RigidSquare-SemiBold.ttf",
      weight: "600",
    },
    {
      path: "../../public/fonts/RigidSquare-Regular.ttf",
      weight: "400",
    },
    {
      path: "../../public/fonts/RigidSquare-Light.ttf",
      weight: "300",
    },
    {
      path: "../../public/fonts/RigidSquare-Thin.ttf",
      weight: "200",
    },
  ],
  variable: "--font-rigidSquare",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${rigidSquare.variable}`}>
      <body>{children}</body>
    </html>
  );
}
